<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Logo-Facebook</name>
   <tag></tag>
   <elementGuidId>aedd5640-41fe-4d42-8a42-270c89f11767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fb_logo._8ilh.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79c49894-8ec6-4ea3-bfd8-6a0674083754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_logo _8ilh img</value>
      <webElementGuid>ff1443d6-6dd0-48dd-9397-8cd83bdf586e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg</value>
      <webElementGuid>66e6d73d-bdbc-49b2-87ba-4f12470413ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>0a95eec4-a1ca-4f88-87cb-120e0a05bb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;_8esj _95k9 _8esf _8opv _8f3m _8ilg _8icx _8op_ _95ka&quot;]/div[@class=&quot;_8esk&quot;]/div[@class=&quot;_8esl&quot;]/div[@class=&quot;_8ice&quot;]/img[@class=&quot;fb_logo _8ilh img&quot;]</value>
      <webElementGuid>0b9fec08-781b-453c-8328-12bdca906275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/img</value>
      <webElementGuid>fb533b04-231f-4696-a205-f64f77d91c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Facebook']</value>
      <webElementGuid>e172a6af-c04f-4b9c-81ab-5b998bdce1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>276cadfc-798f-44fe-bbff-aa8b525e5b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg' and @alt = 'Facebook']</value>
      <webElementGuid>dacd6745-c4de-4777-a224-0e9236cf70b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
